### ISSUE TITLE
Reductions are broken on Xilinx FPGAs

### ISSUE THREAD

**Issue by JamieJQuinn** [spcl/dace#1036] opened 2022-06-28 16:48 UTC
**Describe the bug**
When using a reduction (either manual `dace.reduce` or detected e.g. `np.max`) dace generates incorrect FPGA code which fails to compile with the error:

```
/lustre/home/nx08/nx08/jquinn/dace_iterative_solvers/.dacecache/broken_reduction_sym_1/src/xilinx/device/broken_reduction_sym_0_0.cpp: In function 'void broken_reduction_sym_0_0_0(const double*, double&, int)':
/lustre/home/nx08/nx08/jquinn/dace_iterative_solvers/.dacecache/broken_reduction_sym_1/src/xilinx/device/broken_reduction_sym_0_0.cpp:40:34: error: invalid initialization of reference of type 'double*&' from expression of type 'double'
   40 |         reduce_1_0_2(&__A_in[0], __result_out, N);
      |                                  ^~~~~~~~~~~~
/lustre/home/nx08/nx08/jquinn/dace_iterative_solvers/.dacecache/broken_reduction_sym_1/src/xilinx/device/broken_reduction_sym_0_0.cpp:10:47: note: in passing argument 2 of 'void reduce_1_0_2(const double*, double*&, int)'
   10 | void reduce_1_0_2(const double* _in, double*& _out, int N) {
      |                                      ~~~~~~~~~^~~~
gmake[2]: *** [CMakeFiles/broken_reduction_sym_1.dir/lustre/home/nx08/nx08/jquinn/dace_iterative_solvers/.dacecache/broken_reduction_sym_1/src/xilinx/device/broken_reduction_sym_0_0.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/broken_reduction_sym_1.dir/all] Error 2
gmake: *** [all] Error 2
```

**To Reproduce**
Minimal example:
```
import dace
import numpy as np
from dace.transformation.interstate import FPGATransformSDFG

N = dace.symbol("N")

@dace.program
def broken_reduction_sym(A: dace.float64[N]):
    # result = np.min(A)
    result = dace.reduce(lambda a, b: a+b, A)

broken_reduction_sdfg = broken_reduction_sym.to_sdfg()
broken_reduction_sdfg.apply_transformations(FPGATransformSDFG)
broken_reduction = broken_reduction_sdfg.compile()
```

**Expected behavior**
Reductions should produce code that compiles.

**Additional context**
Dace version: 0.13.2
Vitis version: 2021.2
XRT version: 2.11.634
Python version: 3.9.7
Cmake version: 3.19.3
G++ version: 10.2.0

**Comment by TizianoDeMatteis** [comment] 2022-07-14 16:42
Need to look at this, but makes sense with the error reported above (mix between array and scalar).
Thanks @krishnakumarg1984 for the finding!

**Comment by tbennun** [comment] 2022-07-16 15:43
@JamieJQuinn @krishnakumarg1984 The issue should now be fixed in the latest master branch. Is it also resolved for you?

**Comment by krishnakumarg1984** [comment] 2022-07-17 19:05
@tbennun Yes. Have tested the latest commit on `master`, and can confirm that the issue is now resolved for us. Thank you so much for helping to fix this.

**Comment by tbennun** [comment] 2022-07-17 19:25
We are happy to help, closing the issue :)

**Closed by tbennun** 2022-07-17 19:25 UTC
Labels: bug
