### ISSUE TITLE
Python frontend: Two assignments fail to compile

### ISSUE THREAD

**Issue by tbennun** [spcl/dace#271] opened 2020-05-14 20:30 UTC
In the Python frontend, the following code fails to compile:
```python
@dace.program
def reassign(a: dace.float64[1]):
    s = 0.0
    s = 1.0
```

Due to reassignment of `s`. We should give all variables unique names (if the current name is taken) and reuse them when they are loaded, in order to mimic the interpreter.

**Comment by alexnick83** [comment] 2020-05-14 20:53
Shouldn't this be instead
```python
@dace.program
def reassign(a: dace.float64[1]):
    s = dace.define_local_scalar(dtype=dace.float64)
    s = 0.0
    s = 1.0
```
Scalars can be reassigned (it is interpreted as a value change).

**Comment by tbennun** [comment] 2020-05-14 21:04
The user who wrote the code didn't expect/know that. Can we assume every value set to a new variable is a scalar?

**Comment by htorst** [comment] 2020-05-14 21:06
I agree with Tal (I was that "user" ;-) )

**Comment by alexnick83** [comment] 2020-05-15 08:48
It is not clear to me what is the desired behavior here. First of all, let's clarify that the current behavior is not a bug (in order to ground any expectations that this is a 2 min fix). There are two design decisions at play here; (1) we do not allow redefinition of data, (2) by default variables are implemented as arrays (in this case array of size 1), unless explicitly specified otherwise. Based on the above, the following happens:
- The line `s = 0.0` defines an array s of size 1, with `s[0] = 0.0`.
- The line `s = 1.0` is interpreted as a redefinition of s and the frontend returns an error.

Do we want to change any of the above design decisions? If no, then we can make the following:
- Make it explicit to the user that DaCe does not allow redefinition of data (this should anyway be the current error msg returned).
- The use of `dace.define_local_scalar` is mentioned in the tutorial, but we could enhance it with some actual examples.
- The original code would work if the second statement used the `s[0] = 1.0` or `s[:] = 1.0` notation. We could, however, add a special case, where, if the array has size 1, `s = ...` is interpreted automatically as `s[0] = ...`.

**Closed** 2020-07-16 15:32 UTC
Labels: bug, frontend
