### ISSUE TITLE
Code style issue: classmethod

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#409] opened 2020-10-15 17:35 UTC
**Google styleguide**

> Use classmethod only when writing a named constructor or a class-specific routine that modifies necessary global state such as a process-wide cache.
https://google.github.io/styleguide/pyguide.html#2174-decision

**Example**

https://github.com/spcl/dace/blob/22fd2d20b896b58a39f5dedc698d0807296767a5/dace/transformation/transformation.py#L174

**Possible solution**

Define function outside of class

**Comment by tbennun** [comment] 2020-10-16 07:17
Closed as duplicate of #408

**Closed by tbennun** 2020-10-16 07:17 UTC
