### ISSUE TITLE
Variable shadowing issue after applying FPGA transform in implicit notation

### ISSUE THREAD

**Issue by manuelburger** [spcl/dace#135] opened 2020-02-20 12:04 UTC
Running this code:

```
import dace
import numpy as np


n = dace.symbol("n")

@dace.program
def dot(x: dace.float32[n], y: dace.float32[n], result: dace.float32[1]):

    @dace.map(_[0:n])
    def product(i):
        x_in << x[i]
        y_in << y[i]

        result_out >> result(1, lambda a, b: a + b)
        result_out = x_in * y_in

# ----------
# MAIN
# ----------
if __name__== "__main__":
    a = np.array([1,2,3,4,5,6], dtype=np.float32)
    b = np.array([1,2,3,4,5,6], dtype=np.float32)
    c = np.array([0], dtype=np.float32)

    dot_sdfg = dot.to_sdfg()

    dot_sdfg(x=a, y=b, result=c, n=a.shape[0])
    print("Vec a: ", a)
    print("Vec b: ", b)
    print(c)
```

After applying "FPGATransformSDFG" the tasklet in connector and the inner state source memlet have a name clash i.e. produce a shadowing issue. See also in the attached image of the SDFG generated by the code after applying the FPGA transformation.
<img width="497" alt="Screenshot 2020-02-20 at 12 57 29" src="https://user-images.githubusercontent.com/11148735/74931838-c3bdd880-53e0-11ea-8530-78d5ddd83214.png">

Last lines of error output:
```
  File "/home/burgerm/dace/dace/codegen/targets/cpu.py", line 464, in _emit_copy
    "    " + self.memlet_definition(sdfg, memlet, False, vconn),
  File "/home/burgerm/dace/dace/codegen/targets/cpu.py", line 975, in memlet_definition
    allow_shadowing=allow_shadowing)
  File "/home/burgerm/dace/dace/codegen/targets/target.py", line 226, in add
    raise dace.codegen.codegen.CodegenError(err_str)
dace.codegen.codegen.CodegenError: Shadowing variable x_in from type DefinedType.Pointer to DefinedType.Scalar
```

**Comment by definelicht** [comment] 2020-02-20 15:00
@tbennun @alexnick83 I think this is a coincidence because we use a fairly arbitrary naming scheme, that can potentially clash with users naming their variables the same (in this case `x` -> `x_in`).

**Comment by alexnick83** [comment] 2020-02-20 15:58
@definelicht The problem is actually in NestSDFG. There we append '_in' and '_out' to the names of the data.
@manuelburger I don't think that shadowing is an actual issue here. We will probably change how the names are generated to avoid this, but in the meantime you can set the compiler:allow_shadowing flag to true in the .dace.conf file (in your home folder). This will change the error above to a warning.

**Comment by alexnick83** [comment] 2020-02-20 21:41
@manuelburger Can you check if the latest master fixes your issue?

**Comment by manuelburger** [comment] 2020-02-21 15:46
Code generation is now successful, there seems to be an issue now upon compilation, because the accessed array and the element which is assigned to from the ArrayView have the same name.
See following error output:

```
Applied 2 StateFusion, 1 InlineSDFG.
0. Transformation FPGATransformSDFG in dot
1. Transformation FPGATransformState in s11_4
2. Transformation GPUTransformLocalStorage in product[i=0:n]
3. Transformation GPUTransformMap in product[i=0:n]
4. Transformation GPUTransformSDFG in dot
5. Transformation MapTiling in product: ['i']
6. Transformation MapToForLoop in product: ['i']
7. Transformation NestSDFG in dot
8. Transformation StripMining in product: ['i']
Select the pattern to apply (0 - 8 or name$id): 0
You selected (0) pattern FPGATransformSDFG in dot with parameters {}
WARNING: FPGATransformSDFG::can_be_applied triggered a KeyError exception: '__x_in'
WARNING: FPGATransformState::can_be_applied triggered a KeyError exception: '__x_in'
0. Transformation CopyToDevice in dot
1. Transformation GPUTransformLocalStorage in product[i=0:n]
2. Transformation GPUTransformMap in product[i=0:n]
3. Transformation GPUTransformSDFG in dot_1
4. Transformation GPUTransformSDFG in dot
5. Transformation InlineSDFG in dot
6. Transformation MapTiling in product: ['i']
7. Transformation MapToForLoop in product: ['i']
8. Transformation NestSDFG in dot_1
9. Transformation NestSDFG in dot
10. Transformation StateFusion in dot -> post_dot
11. Transformation StateFusion in pre_dot -> dot
12. Transformation StripMining in product: ['i']
Select the pattern to apply (0 - 12 or name$id):
You did not select a valid option. Quitting optimization ...
-- Using user defined directory: /opt/Xilinx/Vitis/2019.2
-- Found Xilinx Runtime (XRT): /opt/xilinx/xrt
-- Enabled debugging/profiling for Xilinx targets.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/build

[ 33%] Built target dacestub_dot
[ 50%] Building CXX object CMakeFiles/dot.dir/home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/src/xilinx/device/dot.cpp.o
/home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/src/xilinx/device/dot.cpp: In function ‘void module_dot(dace::vec<float, 1>*, dace::vec<float, 1>*, dace::vec<float, 1>*, int)’:
/home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/src/xilinx/device/dot.cpp:30:78: error: use of ‘__x_in’ before deduction of ‘auto’
                             auto __x_in = dace::ArrayViewIn<float, 0, 1, 1> (__x_in + i);
                                                                              ^~~~~~
/home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/src/xilinx/device/dot.cpp:31:70: error: expected primary-expression before ‘)’ token
                             dace::vec<float, 1> x_in = __x_in.val<1>();
                                                                      ^
/home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/src/xilinx/device/dot.cpp:32:78: error: use of ‘__y_in’ before deduction of ‘auto’
                             auto __y_in = dace::ArrayViewIn<float, 0, 1, 1> (__y_in + i);
                                                                              ^~~~~~
/home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/src/xilinx/device/dot.cpp:33:70: error: expected primary-expression before ‘)’ token
                             dace::vec<float, 1> y_in = __y_in.val<1>();
                                                                      ^
/home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/src/xilinx/device/dot.cpp:35:86: error: use of ‘__result_out’ before deduction of ‘auto’
                             auto __result_out = dace::ArrayViewOut<float, 0, 1, 1> (&__result_out);
                                                                                      ^~~~~~~~~~~~
/home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/src/xilinx/device/dot.cpp:13:15: warning: unused variable ‘__x_in’ [-Wunused-variable]
         auto *__x_in = ____x_in.ptr<1>();
               ^~~~~~
/home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/src/xilinx/device/dot.cpp:15:15: warning: unused variable ‘__y_in’ [-Wunused-variable]
         auto *__y_in = ____y_in.ptr<1>();
               ^~~~~~
In file included from /home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/src/xilinx/device/dot.cpp:2:0:
/home/burgerm/dace/dace/codegen/../runtime/include/dace/math.h: At global scope:
/home/burgerm/dace/dace/codegen/../runtime/include/dace/math.h:108:43: warning: ‘dace::math::pi’ defined but not used [-Wunused-variable]
         static DACE_CONSTEXPR typeless_pi pi{};
                                           ^~
CMakeFiles/dot.dir/build.make:75: recipe for target 'CMakeFiles/dot.dir/home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/src/xilinx/device/dot.cpp.o' failed
make[2]: *** [CMakeFiles/dot.dir/home/burgerm/thesis_dace/tasks/intro/.dacecache/dot/src/xilinx/device/dot.cpp.o] Error 1
CMakeFiles/Makefile2:334: recipe for target 'CMakeFiles/dot.dir/all' failed
make[1]: *** [CMakeFiles/dot.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Traceback (most recent call last):
  File "/home/burgerm/dace/dace/codegen/compiler.py", line 595, in configure_and_compile
    output_stream=output_stream)
  File "/home/burgerm/dace/dace/codegen/compiler.py", line 666, in _run_liveoutput
    output.getvalue())
subprocess.CalledProcessError: Command 'cmake --build . --config Release' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "blas_dot.py", line 29, in <module>
    dot_sdfg(x=a, y=b, result=c, n=a.shape[0])
  File "/home/burgerm/dace/dace/sdfg.py", line 1784, in __call__
    binaryobj = self.compile()
  File "/home/burgerm/dace/dace/sdfg.py", line 1700, in compile
    shared_library = compiler.configure_and_compile(program_folder)
  File "/home/burgerm/dace/dace/codegen/compiler.py", line 599, in configure_and_compile
    raise CompilationError('Compiler failure')
dace.codegen.compiler.CompilationError: Compiler failure
```

Caused by the generated code here:
```
 30                             auto __x_in = dace::ArrayViewIn<float, 0, 1, 1> (__x_in + i);
 31                             dace::vec<float, 1> x_in = __x_in.val<1>();
 32                             auto __y_in = dace::ArrayViewIn<float, 0, 1, 1> (__y_in + i);
 33                             dace::vec<float, 1> y_in = __y_in.val<1>();
 34
 35                             auto __result_out = dace::ArrayViewOut<float, 0, 1, 1> (&__result_out);
 36                             dace::vec<float, 1> result_out;
 37
 38                             ////////////////////
 39                             // Tasklet code (product)
 40                             result_out = (x_in * y_in);
```

both the assigned local variable in the inner loop and the access in the ArrayView have same name now, and the tasklets variable for the actual computation never actually get assigned.

**Comment by tbennun** [comment] 2020-02-22 10:14
@alexnick83 the choice of prepending two underscores is unfortunate, as it happens too often in the codebase

**Comment by definelicht** [comment] 2020-04-03 09:25
What was the conclusion here? Is this just an unlucky name clash which we're not gonna fix for now?

**Comment by alexnick83** [comment] 2020-04-03 13:32
I didn't work more on this. The conclusion was that we will introduce in the future a more robust variable/connector name generation.

**Comment by definelicht** [comment] 2020-04-03 13:34
@manuelburger Can you work around this? Then I will close this issue for now.

**Closed by definelicht** 2020-04-03 13:34 UTC
Labels: bug, transformations

**Comment by manuelburger** [comment] 2020-04-03 15:33
Yeah, this is ok for now.
