### ISSUE TITLE
Frontend//Transformation Bug

### ISSUE THREAD

**Issue by sancierra** [spcl/dace#352] opened 2020-08-31 12:09 UTC
The following program returns a wrongly parsed SDFG  (Inside maps should be serially connected and not parallel to each other)

```python
import dace
import numpy as np

@dace.program
def reproducer(A: dace.float64[20], B: dace.float64[20]):
    tmp = np.ndarray([20], dace.float64)
    for k in dace.map[0:2]:
        @dace.map
        def s1(i: _[0:10]):
            a << A[k * 10 + i]
            t >> tmp[K * 10 + i]
            t = a + 1

        @dace.map
        def s2(i: _[0:10]):
            t << tmp[k * 10 + i]
            b >> B[K * 10 + i]
            b = t * 2
```

**Comment by tbennun** [comment] 2020-09-29 21:31
I can verify that the issue is in the frontend. `__tmp_lap_910` is incorrectly defined in the nested SDFG as two different arrays. If `__tmp_lap_910` is placed inside the `k` map then the generated SDFG is correct.

@alexnick83 anything we can do about it? I think it was the intended behavior to create new connectors in nested SDFGs for every access, but it might be better to find the overall region accessed (through union) and use one connector for each array.

**Comment by alexnick83** [comment] 2020-09-30 09:01
@tbennun The issue is in the code. The first access is `tmp[K * 10 + i]` (note the capital K, which is not defined), while the second one is `tmp[k * 10 + i]` (note the small k, which is the iteration variable of the outer map). If you substitute the capital K with a small k, all is fine by design.

There is a general issue with multiple connectors per array and overlapping subsets. However, the generated SDFGs are correct. The issues occur only when you apply strict transformations, which fail to account for those cases. It is a complicated issue for two reasons:
- It is not easy to do it in the frontend; you would have to continuously update the connectors and the memlet subsets. Probably a separate pass after the initial SDFG is generated would be much easier to implement.
- It is not clear that such a thing would even desirable. Since the (true) union will most likely not be rectangular, you would have to overapproximate. This in turn means that in many cases, if you later want to add local storage, that you will copy much more than you need (performance issues).

Fundamentally, the issue is that NestedSDFGs are prone to aliasing, especially since data may need both input and output connectors. We could try to make a RemoveAliasing pass and see what happens. I do not have an ETA though.

For this issue, please verify the symbol fix and close.

**Comment by tbennun** [comment] 2020-09-30 09:03
@alexnick83 actually I edited the sample to simplify, but it's the same behavior:
```python
datatype = dace.float64
I = dace.symbol('I')
J = dace.symbol('J')
K = dace.symbol('K')
halo = dace.symbol('halo')

@dace.program
def stencil_simple(w_in: datatype[J, K+1, I], crlatu: datatype[J], \
                   crlato: datatype[J], hdmask: datatype[J, K+1, I], \
                   w: datatype[J, K+1, I]):

    __tmp_lap_910 = np.ndarray([J, K+1, I], datatype)
    for k in dace.map[0:K]:
        @dace.map
        def s1(x: _[halo-1:J-halo+1], y: _[0:1], z: _[halo-1:I-halo+1]):
            w_in_in << w_in[x-1:x+2, y+k, z-1:z+2]
            crlato_in << crlato[x]
            crlatu_in << crlatu[x]

            __tmp_lap_910_out >> __tmp_lap_910[x,y,z]

            do_something()

        @dace.map
        def s2(x: _[halo:J-halo], y: _[0:1], z:_[halo:I-halo]):
            w_in_in << w_in[x-1:x+2, y+k, z-1:z+2]
            crlato_in << crlato[x]
            hdmask_in << hdmask[x, y+k, z]
            __tmp_lap_910_in << __tmp_lap_910[x-1:x+2, y+k, z-1:z+2]

            w_out >> w[x,y+k,z]


            do_something()
```

**Comment by alexnick83** [comment] 2020-09-30 09:14
This doesn't validate in master without strict transformations. I am not sure why with strict transformations it skips the validation and then it is somehow fixed. I will have to investigate what the issue is and whether it has been fixed in another branch. However, what I wrote above still stands. If there is a read after write on the same subset, then you have only the write connector produced by design and there is no aliasing.

**Closed** 2020-11-09 22:47 UTC
Labels: frontend
