### ISSUE TITLE
Calling A @ B as a dace.program inside a function gives the wrong result

### ISSUE THREAD

**Issue by Simeonedef** [spcl/dace#701] opened 2021-05-04 08:02 UTC
**Describe the bug**
Using dace.program A @ B returns different result than just calling A @ B. This issue doesn't seem to happen when I call it from the main method, but when it's nested inside a more complex function, the results are wrong.

**To Reproduce**
I have  a method that calls a matrix matrix multiplication like so:
`C[m1:m,0:B_dim] += A[m1:m,0:m1] @ B[0:m1,0:B_dim]`
And I attempted to replace it with:
`C[m1:m, 0:B_dim] += matmul_lib(A[m1:m,0:m1],B[0:m1,0:B_dim])`
Where:
`@dace.program
def matmul_lib(A: dtype[M, K], B: dtype[K, N]):
    return A @ B`

**Expected behavior**
They should return the same numerical result, but for some reason they do not. When looking at the numbers produced, the first row seems to correspond but the  rows after are all wrong.
Example:
This is what I get from calling simply A @ B which gives me the correct result:
0.99134411 2.37927192 0.6220935 1.92701032 0.96556958 1.42080484 0.83607334 0.86882378
1.82525592 2.89202545 1.35001469 2.37230364 1.44825839 1.81533188 1.29120714 1.11907193
1.80647289 1.72074369 1.32760667 1.88492459 1.67942782 1.52714228 1.53037621 0.79207197
1.88622792 2.82863798 1.24272828 2.70113389 2.19127038 2.11175294 1.71630729 1.28087929

This is what I get from calling it through matmul_lib:
0.99134411 2.37927192 0.6220935 1.92701032 0.96556958 1.42080484 0.83607334 0.86882378
0.80634312 1.64045609 0.5430692 1.04235601 0.9985718 1.39916937 0.73351313 0.86935447
1.95304681 2.74536479 1.56036938 2.40742907 1.69156976 1.96556436 1.48281472 1.27695084
0.90018296 2.24500806 0.64027737 1.62140514 1.39162286 1.60093125 0.99937141 0.96864924

**Desktop (please complete the following information):**
 - OS: windows 10
 - DaCe on commit: 4f36b20e602a0320ce8303aafcfd9d430d1614e7
 - python 3.7.9

**Comment by tbennun** [comment] 2021-05-04 22:41
@alexnick83

**Comment by alexnick83** [comment] 2021-05-05 07:19
Hello @Simeonedef ! Could you provide us with some extra information? The function calling matmul_lib is also a DaCe program or is it just a normal method executed through the Python interpreter? Also, what is your selected BLAS library default implementation? If you are not sure what it is, you can just attach your `.dace.conf` file, which should be in your home folder (`C:\users\<username>`).

**Comment by Simeonedef** [comment] 2021-05-05 08:26
Hello @alexnick83 
The function calling matmul_lib is just a normal method executed through the python interpreter

I can't seem to attach the .dace.conf file, so I'll just copy paste the contents of it here:


cache: name
compiler:
  allow_shadowing: true
  autobuild_bitstreams: true
  build_type: RelWithDebInfo
  cpu:
    args: /O2 /fp:fast /arch:AVX2 /D_USRDLL /D_WINDLL /D__restrict__=__restrict
    executable: ''
    libs: ''
    openmp_sections: true
  cuda:
    args: -std=c++14 -O3 --use_fast_math
    backend: cuda
    cuda_arch: '35'
    default_block_size: 32,1,1
    dynamic_map_block_size: 128,1,1
    dynamic_map_fine_grained: true
    hip_arch: '906'
    hip_args: -std=c++17 -fPIC -O3 -ffast-math -Wno-unused-parameter
    libs: ''
    max_concurrent_streams: 0
    path: ''
    persistent_map_SM_fraction: 1.0
    persistent_map_occupancy: 2
    syncdebug: false
  default_data_types: Python
  fpga_vendor: xilinx
  indentation_spaces: 4
  inline_sdfgs: false
  intel_fpga:
    board: a10gx
    enable_debugging: false
    host_flags: -Wno-unknown-pragmas
    kernel_flags: -fp-relaxed -cl-no-signed-zeros -cl-fast-relaxed-math -cl-single-precision-constant
      -no-interleaving=default
    launch_async: false
    mode: emulator
    path: ''
  library_extension: dll
  library_prefix: ''
  linker:
    args: ''
    executable: ''
  max_stack_array_size: 65536
  mpi:
    executable: ''
  rtl:
    verbose: false
    verilator_enable_debug: false
    verilator_flags: ''
    verilator_lint_warnings: true
  unique_functions: true
  use_cache: false
  xilinx:
    build_flags: ''
    enable_debugging: false
    frequency: ''
    host_flags: -Wno-unknown-pragmas -Wno-unused-label
    mode: simulation
    path: ''
    platform: xilinx_u250_xdma_201830_2
    synthesis_flags: -std=c++11
debugprint: false
diode:
  general:
    library_autoexpand: true
execution:
  general:
    check_args: true
    copycmd_l2r: scp ${srcfile} ${host}:${dstfile}
    copycmd_r2l: scp ${host}:${srcfile} ${dstfile}
    execcmd: ssh ${host} ${command}
    host: localhost
    repetitions: 5
    workdir: /tmp/
  mpi:
    mpiexec: mpirun -n ${num_procs} ${command}
    num_procs: 4
experimental:
  validate_undefs: false
instrumentation:
  papi:
    default_counters: '[''PAPI_TOT_INS'', ''PAPI_TOT_CYC'', ''PAPI_L2_TCM'', ''PAPI_L3_TCM'']'
    overhead_compensation: true
    vectorization_analysis: false
  report_each_invocation: true
library:
  blas:
    default_implementation: pure
    fpga:
      default_stream_depth: 32
    override: false
optimizer:
  automatic_strict_transformations: true
  autooptimize: false
  autospecialize: false
  autotile_partial_parallelism: true
  autotile_size: 128
  detect_control_flow: true
  interface: dace.transformation.optimizer.SDFGOptimizer
  match_exception: false
  save_intermediate: false
  symbolic_positive: true
  transform_on_call: false
  visualize_sdfv: false
profiling: false
profiling_status: true
testing:
  serialization: false
  single_cache: false
treps: 100

**Comment by alexnick83** [comment] 2021-05-05 08:39
Thanks. I will attempt to recreate the issue and will get back to you (if you have some code that exhibits the issue and you are allowed to share, that would also be great).

**Comment by alexnick83** [comment] 2021-05-05 11:08
@Simeonedef 

I wrote the following code to reproduce the issue. It also includes a workaround:
```python
import dace
import numpy as np


M, K, N = (dace.symbol(s, dtype=dace.int64) for s in ('M', 'K','N'))
x0, x1, x2 = (dace.symbol(s, dtype=dace.int64) for s in ('x0', 'x1', 'x2'))
S0, S1, S2, S3, S4, S5 = (dace.symbol(s, dtype=dace.int64)
                          for s in ('S0', 'S1', 'S2', 'S3', 'S4', 'S5'))
dtype = dace.float32
ntype = np.float32


@dace.program
def matmul_lib(A: dtype[M, K], B: dtype[K, N]):
    return A @ B


@dace.program
def matmul_lib2(A: dtype[M, K], B: dtype[K, N]):
    return A[x0:x1, 0:x0] @ B[0:x0, 0:x2]


if __name__ == "__main__":

    from numpy.random import default_rng
    rng = default_rng(42)

    A = rng.random((100, 100), dtype=ntype)
    B = rng.random((100, 100), dtype=ntype)
    C0 = rng.random((100, 100), dtype=ntype)
    C1 = np.copy(C0)
    Cref = np.copy(C0)

    m1, m, B_dim = 10, 60, 100

    Cref[m1:m,0:B_dim] += A[m1:m,0:m1] @ B[0:m1,0:B_dim]

    C0[m1:m, 0:B_dim] += matmul_lib(A[m1:m,0:m1], B[0:m1,0:B_dim])
    print(np.allclose(C0, Cref))

    C1[m1:m, 0:B_dim] += matmul_lib2(A, B, x0=m1, x1=m, x2=B_dim)
    print(np.allclose(C1, Cref))
```

The issue is related to how we pass NumPy arrays from the CPython interpreter to a generated-by-DaCe shared library. We pass the pointer to the first memory location, and then we expect that the array (or array slice) is contiguous. For example, when you pass `A[m1:m,0:m1]` from Python to the DaCe program, what is actually passed is a pointer (to the underlying C-array) to the memory location of the array element `A[m1,0]`, and the size of the slice `(m-m1) x m1`. Furthermore, the slice is assumed to be contiguous, i.e., it is expected that the next element in memory after `A[m1,m1-1]` in the underlying C-array is `A[m1+1,0]`, which is incorrect since the next element is `A[m1,m1]`. This is why the first row is correct, but the rest of the output is wrong. Let me also clarify that when you do array slicing inside a DaCe program, it works exactly as you expect it. We do not support this slicing **only** when exchanging data between the Python interpreter and the compiled shared library. 

I am not sure what is your exact use case, but I included in the above code a workaround in the form of the DaCe program `matmul_lib2`. This program gets as input the whole arrays A and B and the indices m1, m, and B_dim required to slice A and B appropriately. Alternatively, you could first make a contiguous copy of the arguments with `numpy.copy` and then pass them to the DaCe program, but that could be more expensive.

**Comment by Simeonedef** [comment] 2021-05-05 11:59
Hi @alexnick83 
Thanks for the fast response !

I tried your workaround, but I seem to be running into another issue now where I get the following error: "TypeError: Expression cannot be evaluated to a constant"

```python
STRMM_NB = 4

np.random.seed(10)

# Define symbolic sizes for arbitrary inputs
M, K, N, P, Q = (dace.symbol(s) for s in 'MKNPQ')
x0, x1, x2 = (dace.symbol(s, dtype=dace.int64) for s in ('x0', 'x1', 'x2'))

# Define data type to use
dtype = dace.float64
np_dtype = np.float64
data_index = dace.int32

def initMatrix(m):
    A = np.zeros((m, m), dtype=np_dtype)
    for i in range(0,m):
        for j in range(0,i+1):
            A[i,j] = np.random.rand(1).astype(np_dtype)

    # printMatrix(A,m)
    return A

def magma_get_strmm_nb(n):
    if n > 2048:
        return 2048
    elif n > 1024:
        return 1024
    elif n > 512:
        return 512
    elif n > 256:
        return 256
    elif n > 128:
        return 128
    elif n > 64:
        return 64
    elif n > 32:
        return 32
    elif n > 16:
        return 16
    elif n > 8:
        return 8
    elif n > 4:
        return 4
    elif n > 2:
        return 2
    else:
        return 1

@dace.program
def matmul_lib2(A: dtype[M, K], B: dtype[K, N]):
    return A[x0:x1, 0:x0] @ B[0:x0, 0:x2]

def trmm(A: dtype[M, K], B: dtype[K, N], C: dtype[M, N]):
    N = B.shape[1]
    M = A.shape[0]
    for j in range(0,N):
        for k in range(0,M):
            if(B[M - k - 1,j] != 0):
                tmp = B[M - k - 1,j]
                C[M - k - 1,j] = tmp
                C[M - k - 1, j] *= A[M - k - 1,M - k - 1]
                for i in range(M-k,M):
                    C[i, j] += tmp * A[i, M - k - 1]

def magma_trmm_small(A, m,n, B, B_dim, C):
    trmm(A,B,C)

def magma_trmm(A, m,n, B, B_dim, C):
    global rec_count, STRMM_NB
    if (m <= STRMM_NB):
        magma_trmm_small(A, m,n, B, B_dim, C)
        return

    m1 = magma_get_strmm_nb(m)
    m2 = m - m1

    #bottom triangle
    magma_trmm(A[m1:m,m1:m],m2,n,B[m1:m,0:B_dim], B_dim, C[m1:m,0:B_dim])

    #top triangle
    magma_trmm(A[0:m1, 0:m1], m1, n, B[0:m1, 0:B_dim], B_dim, C[0:m1, 0:B_dim])

    #middle square
    # C[m1:m,0:B_dim] += A[m1:m,0:m1] @ B[0:m1,0:B_dim]
    C[m1:m, 0:B_dim] += matmul_lib2(A[m1:m,0:m1],B[0:m1,0:B_dim])

if __name__ == "__main__":
# Prepare data with numpy
    m = args["M"]
    A = initMatrix(m)
    B = np.random.rand(m, m)
    C = np.zeros((m, m), dtype=np_dtype)

    print(f'TRMM multiplication {m}x{m}x{m} (version: {version})')
    magma_trmm(A, m,m, B, m, C)
```

**Comment by Simeonedef** [comment] 2021-05-05 12:41
Hi @alexnick83 

Thanks for the fast response ! 
Oh right this makes sense, your workaround fixed it, thank you !

**Comment by alexnick83** [comment] 2021-05-24 21:28
I am closing this since the issue has been resolved. Please let us know if you have any other issues!

**Closed by alexnick83** 2021-05-24 21:28 UTC
Labels: bug, frontend
